### ISSUE TITLE
About code ERESOLVE

### ISSUE THREAD

**Issue by mjjeon2645** [zacanger/styled-reset#21]
Hello!

I've installed latest version of styled-components because of some errors about that.
link: https://github.com/styled-components/styled-components/issues/3998

So I used this line.
`npm i styled-components@latest`

Then I tried to install styled-reset but it was not working.
Iterm showed me the error code 'ERESOLVE' and I think it might be conflict of versions.
It could not resolve dependency either. 

Is there any solution to install styled-reset?
Is it right of version conflict between styled-components and styled-reset?

**Comment by zautumnz** [comment]
안녕하세요, for the moment, you'll need to use `npm i styled-components@5` instead of `@latest`. It looks like the SC team started publishing the release candidates using the main publish config, but v6 still is not stable. When it is released (as a stable version) I'll update this package if there are breaking changes.

When styled 6 reaches stable, the current version of styled-reset will have a warning on install about an unmet peer dependency, but I'll get that updated just as soon as they publish their migration docs.

If the above fix (using `styled-components@5` instead of `latest`) doesn't work for you, please let me know and I'll re-open this issue and investigate this weekend.

**Comment by mjjeon2645** [comment]
> 안녕하세요, for the moment, you'll need to use `npm i styled-components@5` instead of `@latest`. It looks like the SC team started publishing the release candidates using the main publish config, but v6 still is not stable. When it is released (as a stable version) I'll update this package if there are breaking changes.
> 
> When styled 6 reaches stable, the current version of styled-reset will have a warning on install about an unmet peer dependency, but I'll get that updated just as soon as they publish their migration docs.
> 
> If the above fix (using `styled-components@5` instead of `latest`) doesn't work for you, please let me know and I'll re-open this issue and investigate this weekend.

Oh. It's working right. Thank you!
